### ISSUE TITLE
Add MWAX_VCS option from_channel and to_channel

### ISSUE THREAD

**Issue by gsleap** [MWATelescope/giant-squid#25]

**Comment by Mouriyan-Rajendran** [comment]
Refer: https://github.com/MWATelescope/manta-ray/issues/342

Don't add any new arguments if data range is not selected

**parameters to apply channel range:**
channel_range = true
from_channel = integer
to_channel = integer 

conditions:

- channel_range in a boolean
- from_channel and to_channel are integers with values  between 0 and 255 inclusively,
- to_channel must be greater than from_channel

**Comment by gsleap** [comment]
Fixed by 715236acc9ae09ae7965f3e28fddda1efccb3011
