### ISSUE TITLE
segfault when listing jobs

### ISSUE THREAD

**Issue by d3v-null** [MWATelescope/giant-squid#5]
I can submit jobs just fine, but I get a segfault when listing jobs. Probably another prettytable issue

```txt
> giant-squid list
zsh: segmentation fault (core dumped)  giant-squid list
```

**Comment by d3v-null** [comment]
yup

![image](https://user-images.githubusercontent.com/2578076/224880016-52e2c2f1-2557-4e22-83f3-c72cc87dfabe.png)

**Comment by cjordan** [comment]
Please update the prettytable version and we'll stop getting that annying github security advisory.
